---
# config proxy https://elegantinfrastructure.com/docker/ultimate-guide-to-docker-http-proxy-configuration/

- name: devops | docker | install requisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: present
  become: true
  tags:
    - devops
    - docker

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html
# The apt-key command has been deprecated and suggests to 'manage keyring files in trusted.gpg.d instead'.

- name: devops | docker | agrega clave del repo
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg"
    mode: "0644"
    dest: /usr/share/keyrings/docker.asc
    force: true
  become: true
  tags:
    - devops
    - docker

- name: devops | docker | aseguro que /etc/default/docker no existe en systemd
  ansible.builtin.file:
    path: /etc/default/docker
    state: absent
  become: true
  when: ansible_facts['service_mgr'] == 'systemd'
  tags:
    - devops
    - docker

- name: devops | docker | agrego repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}  {{ ansible_facts['distribution_release'] }} stable"
    state: present
    update_cache: true
    filename: docker
  become: true
  register: reg_add_repo_docker
  tags:
    - devops
    - docker

- name: devops | docker | actualizo lista paquetes .deb
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: reg_add_repo_docker is changed
  tags:
    - devops
    - docker

- name: devops | docker | instala docker-ce
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
  become: true
  tags:
    - devops
    - docker

- name: devops | docker | Ensure 'docker' group exists
  ansible.builtin.group:
    name: docker
  become: true
  tags:
    - devops
    - docker

- name: devops | docker | "Add users to 'docker' group."
  ansible.builtin.user:
    name: "{{ docker_user_name }}"
    groups:
      - docker
    append: true
  become: true
  tags:
    - devops
    - docker

- name: devops | docker | Make sure that systemd directory exists
  ansible.builtin.file:
    path: "/etc/systemd/system"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  when: ansible_facts['service_mgr'] == 'systemd'
  become: true
  tags:
    - devops
    - docker

- name: devops | docker | Make sure that docker.service.d directory exists
  ansible.builtin.file:
    path: "/etc/systemd/system/docker.service.d"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  when: (ansible_facts['service_mgr'] == 'systemd' and (docker__env_http_proxy is defined or docker__env_https_proxy is defined))
  become: true
  tags:
    - devops
    - docker

- ansible.builtin.debug: var=docker__env_https_proxy
  tags:
    - devops
    - docker

- ansible.builtin.debug: var=https_proxy
  tags:
    - devops
    - docker

- name: devops | docker | configura proxy
  ansible.builtin.template:
    src: "http-proxy.conf.j2"
    dest: "/etc/systemd/system/docker.service.d/http-proxy.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  register: reg_docker_proxy
  when: (ansible_facts['service_mgr'] == 'systemd' and (docker__env_http_proxy is defined or docker__env_https_proxy is defined))
  vars:
    __env_http_proxy: "{{ docker__env_http_proxy }}"
    __env_https_proxy: "{{ docker__env_https_proxy }}"
    __env_no_proxy: "{{ docker__env_no_proxy}}"
  tags:
    - devops
    - docker

- name: devops | docker | docker deamon is running
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: docker
  become: true
  when: reg_docker_proxy is changed
  tags:
    - devops
    - docker
