---
- name: eclipse | instala desde snap
  community.general.snap:
    name: eclipse
    classic: true
  become: true
  ignore_errors: true  # community.general.snap module crashes with "list index out of range" on GitHub Actions runners where snapd cannot query the snap store
  tags:
    - eclipse
