---
- name: bitwarden | instala desde snap
  community.general.snap:
    name:
      - bw
      - bitwarden
  become: true
  ignore_errors: true  # community.general.snap module crashes with "list index out of range" on GitHub Actions runners where snapd cannot query the snap store
  tags:
    - bitwarden
