---
- name: bitwarden | instala desde snap
  community.general.snap:
    name:
      - bw
      - bitwarden
  become: true
  ignore_errors: "{{ lookup('env', 'CI') | default(false) | bool }}"
  tags:
    - bitwarden
