---
# https://netbeans.apache.org/kb/docs/php/index.html
# https://netbeans.org/kb/trails/php.html
# https://stackoverflow.com/questions/48317705/how-to-install-symfony4-in-netbeans
# https://somospnt.com/blog/31-apache-netbeans-11-como-configurar-el-ide-para-aprovecharlo-al-maximo

- name: netbeans | actualizo lista paquetes .deb
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true
  tags:
    - netbeans

- name: netbeans | instala Open JDK 11
  ansible.builtin.apt:
    name:
      - openjdk-11-jdk
    state: present
  become: true
  tags:
    - netbeans

- name: netbeans | instala desde snap
  community.general.snap:
    name: netbeans
    classic: true
  become: true
  ignore_errors: "{{ lookup('env', 'CI') | default(false) | bool }}"  # community.general.snap module crashes on GitHub Actions runners where snapd cannot query the snap store
  tags:
    - netbeans
