---
galaxy_info:
  role_name: docker
  author: CesarBallardini
  description: Install Docker CE with proxy configuration
  min_ansible_version: "2.17"
  license: MIT
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
        - resolute
    - name: Debian
      versions:
        - trixie
        - forky
  galaxy_tags:
    - docker
    - containers
    - devops

dependencies: []
