---
- name: tinyproxy | instala paquete
  ansible.builtin.apt:
    name: tinyproxy
  become: true
  tags: [tinyproxy, proxy]

- name: tinyproxy | package facts
  ansible.builtin.package_facts:
    manager: auto
  tags: [tinyproxy, proxy]

- name: tinyproxy | configuracion pre 1.8.4
  ansible.builtin.template:
    src: "tinyproxy.conf-pre1.8.4.j2"
    dest: "/etc/tinyproxy/tinyproxy.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  when: ansible_facts.packages['tinyproxy'][0].version is version('1.8.4', operator='le')
  notify: tinyproxy | daemon restarted
  tags: [tinyproxy, proxy]

- name: tinyproxy | configuracion post 1.10.0
  ansible.builtin.template:
    src: "tinyproxy.conf.j2"
    dest: "/etc/tinyproxy/tinyproxy.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  when: ansible_facts.packages['tinyproxy'][0].version is version('1.8.4', operator='gt')
  notify: tinyproxy | daemon restarted
  tags: [tinyproxy, proxy]
